### ISSUE TITLE
Add commandline argument parsing with argparse

### ISSUE THREAD

**Issue by jd7h** [jd7h/tuvok#1]

**Comment by jmeline** [comment]
Which command line arguments are you looking to support? I see that you've got IMDB-id and a minimum rating so far, are there any others? I wouldn't mind tackling this for ya. Would you mind assigning it to me?

**Comment by jd7h** [comment]
Just those two are fine. :) Good luck.

**Comment by jmeline** [comment]
well someone else got to it... Anyways interesting little project you've got there. Best wishes.
